version: '3.8'

services:
  # 1. MySQL 
  mysql:
    image: mysql:8.0
    container_name: Capstone_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: GameDB
    ports:
      - "3306:3306" 
    command: --default-authentication-plugin=mysql_native_password

  # 2. Redis 
  redis:
    image: redis:alpine
    container_name: Capstone_redis
    ports:
      - "6379:6379" 